#!/usr/bin/env python2.7
#--coding:utf-8 --
"""
jd2juice
2017-08-10
"""
__date__ = "2017-08-10"
__modified__ = ""
__email__ = "caoyaqiang@picb.ac.cn"

#general library
import os

#cLoops
from cLoops.io import pet2hic
from cLoops.utils import pet2juiceHelp

if __name__ == "__main__":
    op = pet2juiceHelp()
    pet2hic(op.input, op.output + "_juice.hic", op.cut, op.org,
            op.strict_intra_flag)
